spring:
  application:
    name: springboot-and-mongodb
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: simpleDB # need to manually create this db on mongo-express
      port: 27017
      host: localhost
server:
  port: 8080
